version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Expose Flask app on localhost:5000
    environment:
     - .env 
    depends_on: 
     - db # Ensure DB starts before the web app
    volumes:
      - .:/app  # Mount project directory into the container
    working_dir: /app  # Set working directory explicitly

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist DB data

volumes:
  postgres-data:

