pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "your-dockerhub-username/mini-project-5-flask-users"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('mini-project-5-flask-users') {
                    script {
                        docker.build(DOCKER_IMAGE, '.')
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('mini-project-5-flask-users') {
                    script {
                        docker.image(DOCKER_IMAGE).inside {
                            sh 'pytest tests'
                        }
                    }
                }
            }
        }

stage('Push Docker Image') {
    steps {
        dir('mini-project-5-flask-users') {
            withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                sh 'docker build -t $DOCKERHUB_USER/mini-project-5-flask-users .'
                sh 'echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin'
                sh 'docker push $DOCKERHUB_USER/mini-project-5-flask-users'
            }
        }
    }
}

        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                echo 'Deploying...'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
