apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-api
  template:
    metadata:
      labels:
        app: taskmanager-api
    spec:
      containers:
      - name: taskmanager-api
        image: gcr.io/devops-lab-464007/taskmanager-api/taskmanager-api:0b77f1c
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@db:5432/postgres"
          - name: JWT_SECRET_KEY
            value: "supersecretkey"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
