apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-api
  template:
    metadata:
      labels:
        app: taskmanager-api
    spec:
      containers:
      - name: taskmanager-api
        image: gcr.io/devops-lab-464007/mini-project-5-flask-users:v1.1.0
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
           value: "your_postgres_url_here"
          - name: JWT_SECRET_KEY
           value: "your_secret_key_here"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

