# Define a Kubernetes Secret for sensitive environment variables
apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secrets
type: Opaque
data:
  jwt-secret-key: c3VwZXJzZWNyZXRrZXk=  # base64 encoded "supersecretkey"
  postgres-password: cG9zdGdyZXM=        # base64 encoded "postgres"
