apiVersion: v1
kind: Service
metadata:
  name: taskmanager-api-service
spec:
  type: LoadBalancer
  selector:
    app: taskmanager-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
