apiVersion: v1
kind: Service
metadata:
  name: taskmanager-api-service
spec:
  type: LoadBalancer  # Let cloud provider expose this service to the internet
  selector:
    app: taskmanager-api
  ports:
    - protocol: TCP
      port: 80         # Browser-friendly port (standard HTTP)
      targetPort: 8000 # Forward to container's port running FastAPI
