pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "nodejsmongoapp"
    }

    stages {
        stage('Build & Start Containers') {
            steps {
                dir('mini-project-3-nodejs-mongo') {
                    sh 'docker compose build'
                    sh 'docker compose up -d'

                }
            }
        }

        stage('Health Check') {
            steps {

                    sh 'sleep 10'
                    sh 'curl -f http://localhost:3000/'


            }
        }
    }

    post {
        failure {
            echo '❌ Build failed!'
        }
        success {
            echo '✅ App deployed successfully!'
        }
    }
}
